name: CI Pipeline - Nextflix-Web-Appliation

on:
  push:
    branches: [main, dev]
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches: [main, dev]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build:
    name: Build & Lint Frontend + Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [frontend, backend]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.app }}

      - name: Run Lint
        run: npm run lint || echo "Lint failed"
        working-directory: ${{ matrix.app }}

      - name: Build Project
        run: npm run build
        working-directory: ${{ matrix.app }}

  deploy-backend:
    name: Deploy Backend to Render
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ github.ref == 'refs/heads/main' && secrets.RENDER_DEPLOY_HOOK_MAIN || secrets.RENDER_DEPLOY_HOOK_DEV }}