name: CI Pipeline - Nextflix-Web-Appliation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint Frontend + Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [frontend, backend]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.app }}

      - name: Run Lint
        run: npm run lint || echo "Lint failed"
        working-directory: ${{ matrix.app }}

      - name: Build Project
        run: npm run build
        working-directory: ${{ matrix.app }}
